kind: pipeline
name: default

steps:
- name: build
  image: frolvlad/alpine-gcc:latest
  commands:
  - gcc -static -Wall -Werror -D_GNU_SOURCE -o distmark distmark.c

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github-token
    files:
      - distmark
    checksum:
      - sha256
  when:
    event: tag
